// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD71Qu26g_zMnFOi90rKwUCOyxPqCsj894',
    appId: '1:9686566444:web:1fc7ba2b4b8af4f9107389',
    messagingSenderId: '9686566444',
    projectId: 'zegocloud-1dbc3',
    authDomain: 'zegocloud-1dbc3.firebaseapp.com',
    storageBucket: 'zegocloud-1dbc3.appspot.com',
    measurementId: 'G-2GSYXVMBRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkbT6jbUJMRTzx2Dv_7anKX9zB0VZ9yO0',
    appId: '1:9686566444:android:10c2849b412b7933107389',
    messagingSenderId: '9686566444',
    projectId: 'zegocloud-1dbc3',
    storageBucket: 'zegocloud-1dbc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF2ioQhZ-GD-AUiyQKFquqpOQokvPLuCo',
    appId: '1:9686566444:ios:32c3bbec6db1caf7107389',
    messagingSenderId: '9686566444',
    projectId: 'zegocloud-1dbc3',
    storageBucket: 'zegocloud-1dbc3.appspot.com',
    androidClientId: '9686566444-tgdqq1ecqsu91084uvh5969so8nht8qs.apps.googleusercontent.com',
    iosClientId: '9686566444-poj126hol6ieos689d337eqj77jvejua.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoVoiceCall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF2ioQhZ-GD-AUiyQKFquqpOQokvPLuCo',
    appId: '1:9686566444:ios:a04b8a176c3f2ff7107389',
    messagingSenderId: '9686566444',
    projectId: 'zegocloud-1dbc3',
    storageBucket: 'zegocloud-1dbc3.appspot.com',
    androidClientId: '9686566444-tgdqq1ecqsu91084uvh5969so8nht8qs.apps.googleusercontent.com',
    iosClientId: '9686566444-ot681a2lmqh78ac6efrdm5i82asktv86.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoVoiceCall.RunnerTests',
  );
}
